# Generated by Django 5.1.5 on 2025-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorImage',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
