# Generated by Django 5.1.5 on 2025-01-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='media/defaultUser.png', upload_to='media/uploads/'),
        ),
    ]
