# Generated by Django 5.1.5 on 2025-01-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
