# Generated by Django 5.1.5 on 2025-01-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='media/defaultUser.png', upload_to='uploads/'),
        ),
    ]
